# Generated by Django 4.2.5 on 2023-09-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_audiorecording"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiorecording",
            name="audio_file",
        ),
        migrations.AddField(
            model_name="audiorecording",
            name="audio_data",
            field=models.BinaryField(default=int),
            preserve_default=False,
        ),
    ]
