# Generated by Django 3.2.5 on 2023-09-22 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_audiorecording_audio_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiorecording',
            name='audio_data',
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='audio_file',
            field=models.FileField(default=int, upload_to='audio_recordings/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
